### ISSUE TITLE
How does this compare to ShortenedThrowableConverter?

### ISSUE THREAD

**Issue by lucarota** [tanersener/smart-exception#11]
Hi,

this library is very interesting, but could you say what the differences are over the ShortenedThrowableConverter in logstash-logback?

Thank you,
Luca

**Comment by tanersener** [comment]
As far as I know, `ShortenedThrowableConverter` does not provide the following features:
- `rootPackages`, ability to define root packages
- `groupPackages`, used to group stack trace elements
- Ability to drop Java module names
- Java API that comes with additional methods e.g. search for a specific exception in an exception chain, customise the log line printed
